---
title: "Lab 3 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Setup

1.  Login to the lab computer (please don't use your personal computer).\
2.  Navigate to github.com and login.\
3.  Copy your repository to the desktop.\
4.  Copy the class repository to the desktop (<https://github.com/jmledford3115/datascibiol>).\
5.  Copy the files for today's lab from the class repository and paste them into **your** repository.\
6.  Open today's lab in RStudio.

## Review from last time

### *With a partner, discuss the following questions*

1.  What are examples of different classes of objects in R?

way to store information

1.  What is a vector? What is the command to make a vector in R?

set of concatenated data (c)

1.  What is a data matrix and how does a data matrix relate to vectors?

stacked vectors; two dimensional

1.  Do you have any questions from homework 2?

your mom

## Warm-up

1.  Build a vector that includes the following height measurements for five plants: plant 1 30.7, plant 2 37.6, plant 3 28.4, plant 4 NA, plant 5 33.2

2.  Build another vector that includes the following mass measurements: plant 1 4, plant 2 5.2, plant 3 3.7, plant 4 NA, plant 5 4.6

3.  Assemble these vectors into a labeled data matrix with two columns

4.  Calculate the mean for height and mass and add them to the data matrix
